name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .deno-version)" >> $GITHUB_ENV
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
          cache: true
          cache-hash: ${{ hashFiles('.deno-version', 'deno.lock') }}
      - name: Run linters
        run:
          deno task check
      - name: deno publish --dry-run
        run:
          deno publish --dry-run
      - name: Run tools/patch.ts
        run: |
          deno task clean:gen
          deno task tools:patch
          git diff --exit-code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run:
          deno task test
  dnt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .deno-version)" >> $GITHUB_ENV
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
          cache: true
          cache-hash: ${{ hashFiles('.deno-version', 'deno.lock') }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
      - name: Run dnt
        run:
          deno task build:npm
      - name: cat package.json
        run: |
          cat npm/package.json
      - name: Run `npm pack --dry-run`
        working-directory: npm
        run: |
          npm pack --dry-run
